### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Sahar-AbdelSamad** [Bondok6/Porfolio-bootstrap#1]
# Hi @Bondok6  👋🏻 

You've done a great job so far :clap: :clap: :clap: 

## To highlight 👍🏻  ## 
:heavy_check_mark: The app is working properly.
:heavy_check_mark: You only used bootstrap and the end result looks very similar to the Figma design
:heavy_check_mark:  I really love it, I learned a lot from your work

## Suggestions ##
- [x] Add the IDs to the navbar, so that when we press on it, it takes us to the corresponding section
- [x] It would be better if you download the Bootstrap in your project since it is required from us in this activity

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)
Cheers and Happy coding! 🎉🎉🎉

**Comment by Bondok6** [comment]
## Hi @Sahar-AbdelSamad  👋

### Thanks for your suggestions 👌

<img src="https://media3.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif"/>
